### ISSUE TITLE
Issues running the .jar file on Windows

### ISSUE THREAD

**Issue by rastenis** [cameronleger/neural-style-gui#7]
Hello,

Please excuse me if this is an issue on my end, but after trying all combinations of OpenJDK and Oracle's JDK and JavaFX, I have good reason to believe it not to be:

This is the error: 
`java.lang.ClassNotFoundException: com.sun.glass.ui.win.WinPlatformFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:333)
        at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:830)
Failed to load Glass factory class
Exception in thread "main" java.lang.NullPointerException
        at com.sun.glass.ui.Application.run(Application.java:144)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:830)
`

I'm running the .jar like this: `java -jar neural-style-gui-1.3.0.jar`

Currently using JDK 13.0.2 and JavaFX 11.0.2

A similar issue is described here: https://github.com/qzind/tray/issues/457

Thank you for any pointers.

**Comment by cameronleger** [comment]
That does make sense, the JAR was built on Linux and not meant to be multi-platform. I can easily build the multi-platform JAR, but I didn't think to because the underlying neural-style script that this relies on (at least I thought) only works on Linux.

Do you have neural-style setup on Windows?

**Comment by rastenis** [comment]
It does not seem to be possible to run neural-style on Windows due to torch being incompatible. I must have been thinking of either https://github.com/fzliu/style-transfer or https://github.com/cysmith/neural-style-tf when I impulse cloned this repo 😅. Sorry for the trouble.

**Comment by cameronleger** [comment]
No worries! I know there's also a pytorch implementation that's very similar in its usage. If any of those work for you, and they have basically the same arguments and features, it's not that hard to make it work with them, so let me know!
